### ISSUE TITLE
JAR produced by boot build does not run

### ISSUE THREAD

**Issue by mprokopov** [oakes/Lightmod#9]
I tried to export several examples and to make `boot build`. The JAR file appears in `target` directory, but when run it silently does nothing.

Platform : mac os sierra, java 8.

**Comment by oakes** [comment]
Hmm I can't reproduce this, same platform as you. Does the jar file [on the website](https://sekao.net/lightmod/) work?

**Comment by mprokopov** [comment]
I mean examples within Lightmod, like isomorphic, chat applications.

**Comment by oakes** [comment]
Oh yes, for the exported jars it won't print anything unless you specifically tell it to in your `server.clj`. For example, if you want it to print what local address it can be accessed with, change your `server.clj` like this:

```diff
+(defn print-server [server]
+  (println (str "Started app on http://localhost:" (-> server meta :local-port) "/index.html"))
+  server)
+
 ; runs when the server starts
 (defn -main [& args]
   (-> #'handler
       (wrap-content-type)
       (wrap-keyword-params)
       (wrap-params)
       (wrap-reload)
       (wrap-resource "isomorphic")
-      (run-server {:port 0})))
+      (run-server {:port 0})
+      print-server))
```

Keep in mind that this will cause `boot run` to print it twice, since it is already doing this in your `build.boot` file. You can fix that by commenting out the line that contains "println" in your `build.boot`.

**Comment by mprokopov** [comment]
Thanks! Much better now )
